
DROP TABLE IF EXISTS file CASCADE;

CREATE TABLE file (
    ufn         VARCHAR(64) NOT NULL,
    uhn         VARCHAR(64) NOT NULL,
    hostname    VARCHAR(255) NOT NULL,
    path        TEXT NOT NULL,
    filename    TEXT NOT NULL,
    crcsum      VARCHAR(64) NOT NULL,
    file_size   INTEGER NOT NULL,
    mod_time    INTEGER NOT NULL,
    block_size  INTEGER NOT NULL,
    compressed  BOOLEAN NOT NULL DEFAULT FALSE,
    dirty       BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE file ADD CONSTRAINT file_pkey PRIMARY KEY (ufn);

COMMENT ON COLUMN  file.ufn IS 'Unique file name: md5sum of uhn + path + filename ';
COMMENT ON COLUMN  file.uhn IS 'Unique host name: random string generated by client';
COMMENT ON COLUMN  file.hostname IS 'Hostname of machine';
COMMENT ON COLUMN  file.path IS 'File path tree';
COMMENT ON COLUMN  file.filename IS 'File name';
COMMENT ON COLUMN  file.crcsum IS 'Checksum of file data';
COMMENT ON COLUMN  file.file_size IS 'File size in bytes';
COMMENT ON COLUMN  file.mod_time IS 'File modified time in Unix epoch';
COMMENT ON COLUMN  file.block_size IS 'Data size in bytes used for transmission and comparison';
COMMENT ON COLUMN  file.compressed IS 'True if data uploaded compressed';
COMMENT ON COLUMN  file.dirty IS 'True if file is currently being synced';



DROP TABLE IF EXISTS file_block CASCADE;

CREATE TABLE file_block (
    file        VARCHAR(64) NOT NULL,
    id          INTEGER NOT NULL,
    crcsum      VARCHAR(64) NOT NULL
);

ALTER TABLE file_block ADD CONSTRAINT file_block_pkey PRIMARY KEY (file,id);
ALTER TABLE file_block ADD CONSTRAINT file_block_fk FOREIGN KEY
    (file) REFERENCES file (ufn) ON DELETE CASCADE ON UPDATE CASCADE;


COMMENT ON COLUMN  file_block.file IS 'Unique file name that block belongs to';
COMMENT ON COLUMN  file_block.id IS 'File block number';
COMMENT ON COLUMN  file_block.crcsum IS 'File block checksum';
